  version: "3.7"
  services:
    redis:
      image: redis
      ports:
        - "${REDIS_PORT}:${REDIS_PORT}"
    mongodb:
      image: mongo
      ports:
        - "${MONGO_PORT}:${MONGO_PORT}"
    config-api:
      build: ./config-api/
      ports:
        - "80:80"
      env_file:
        - .env
    node-sv-history:
      build: ./node-sv-history
      ports: 
        - "$SV_HISTORY_PORT_INT:$SV_HISTORY_PORT_EXT"
    logs-service:
      build: ./logs-service
      ports:
        - "$LOGS_SERVICE_PORT:$LOGS_SERVICE_PORT"