  version: "3.7"
  services:
    redis:
      image: redis
      ports:
        - "${REDIS_PORT}:${REDIS_PORT}"
    mongodb:
      image: mongo
      ports:
        - "${MONGO_PORT}:${MONGO_PORT}"
    config-api:
      build: ./config-api/
      ports:
        - "80:80"
      env_file:
        - .env
      depends_on:
        - redis
      links:
        - redis
    node-sv-history:
      build: ./node-sv-history
      ports: 
        - "$SV_HISTORY_PORT_INT:$SV_HISTORY_PORT_EXT"
      depends_on:
        - redis
        - mongodb
      links:
        - redis
        - mongodb
      environment:
        - MONGO_HOST=$MONGO_HOST
        - MONGO_PORT=$MONGO_PORT
        - MONGO_DB=$MONGO_DB
        - REDIS_HOST=$REDIS_HOST
        - REDIS_PORT=$REDIS_PORT
        - SV_HISTORY_PORT_INT=$SV_HISTORY_PORT_INT
    logs-service:
      build: ./logs-service
      ports:
        - "$LOGS_SERVICE_PORT:$LOGS_SERVICE_PORT"
      depends_on:
        - redis
      links:
        - redis
      environment:
        - SV_HISTORY_HOST=$SV_HISTORY_HOST
        - SV_HISTORY_PORT=$SV_HISTORY_PORT